### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by HurtsAsHell** [HurtsAsHell/Not-Sky-Industry-Public#10]
- [ ] Anvil IE Crafting
- [ ] Rustic Bush Crafting
- [ ] Infinite Ingot Crafting
- [ ] Material Bush Crafting
- [ ] Add Info tab to material dropped from grass
- [ ] Change Menu screen 
- [ ] Add Bug Button ( i need to know the mod name )
- [ ] Add new balls mod
